### ISSUE TITLE
Add plane_shape and plane_zero to individual components vignette

### ISSUE THREAD

**Issue by abenefield1** [signaturescience/rplanes#104]

**Comment by vpnagraj** [comment]
@abenefield1 im expanding scope a bit on this issue ... 

lets fold in updates to the individual component vignette to document `plane_zero()` as well. i just added that function to the package (https://github.com/signaturescience/rplanes/issues/105)

also, i just updated the branch for this issue is to align with dev (as of a few minutes ago) and should have the `plane_shape()` *and `plane_zero()` functions if you pull from it:

https://github.com/signaturescience/rplanes/tree/104-add-plane-shape-to-individual-components-vignette

if you have any questions let me know. i can also chip in on the `plane_zero()` content if needed. i just wanted to consolidate issues where it made sense.

**Comment by vpnagraj** [comment]
added into dev via https://github.com/signaturescience/rplanes/pull/116
