### ISSUE TITLE
New vignette that shows limitations of various components for weighting schemes

### ISSUE THREAD

**Issue by abenefield1** [signaturescience/rplanes#115]
For example, we should show that plane_shape() will flag an epidemic curve like in the example of the US below. To a human who has seen many epidemic curves, we know that this is actually plausible. But to the DTW algorithm, this shape has not been observed in the seed, so it's flagged as implausible.

<img width="236" alt="image" src="https://github.com/signaturescience/rplanes/assets/42815856/a83d11fe-ffff-40c4-885c-bcc07f8fa955">

We can keep notes about what the limitations of various components are here.

This is pretty far down the road in terms of priority, but I figured that opening an issue would allow us to track various limitations as we think about them.

**Comment by vpnagraj** [comment]
thanks for posting this issue @abenefield1 !

agreed this would be useful. maybe we could couch it under a general "Best Practices for Interpretation" or something like that?

that could cover a range of interpretation considerations:

- limitations of depending on seed data as "trusted" source (e.g., the example with DTW flagging the shape because there isn't previous data that exhibits that shape)
- optional weighting schemes (https://github.com/signaturescience/rplanes/issues/107)
- what to "do" with a flagged location (i.e., describe how important it is to do analysis to understand the sensitivity of the score *for the target you are interested in evaluating*)
- {others}

**Comment by abenefield1** [comment]
@vpnagraj , outline is drafted: https://github.com/signaturescience/rplanes/blob/115-new-vignette-that-shows-limitations-of-various-components-for-weighting-schemes/vignettes/interpretaions_limitations.Rmd

I also have a word doc that has a nested outline that makes more sense if you want that.

**Comment by vpnagraj** [comment]
@abenefield1 thanks for getting started on this. as you and i had discussed, it sounds like you may be adding to this outline a bit in the near future. please do keep moving forward with any other additions. 

but i did take a quick look at the outline ... right on track! 

only thing i would say we should add is some context regarding utility of doing a retrospective analysis of scoring and sensitivity (i.e., how many flags are "normal" in the *specific* signal being analyzed) before interpreting the score. maybe that could go in the "What to do when a flag is raised" section?

and the Rmd format is good with me. no Word doc necessary :)

ping me when you've completed any additions => i'll give the outline one more look => we'll start writing.

**Comment by abenefield1** [comment]
@vpnagraj, I made the additional edits we'd discussed. It's still in outline format, and I'm happy to convert to more of an actual document. Let me know what you think.

https://github.com/signaturescience/rplanes/blob/115-new-vignette-that-shows-limitations-of-various-components-for-weighting-schemes/vignettes/interpretaions_limitations.Rmd

**Comment by vpnagraj** [comment]
@abenefield1 im finally getting around to looking at this. outline looks great! green light to start writing in full. keep working on the same branch (115-new-vignette-that-shows-limitations-of-various-components-for-weighting-schemes). and of course when that prose comes together in a draft, tag me for review and we can iterate.

**Comment by abenefield1** [comment]
@vpnagraj, the interpretation vignette is ready to be reviewed: https://github.com/signaturescience/rplanes/blob/115-new-vignette-that-shows-limitations-of-various-components-for-weighting-schemes/vignettes/interpretaions_limitations.Rmd

**Comment by vpnagraj** [comment]
@abenefield1 ive reviewed and updated the vignette ... now merged onto the dev branch via (https://github.com/signaturescience/rplanes/pull/144) ... as we do final cleanup for the v0.1.0 release (#141), i'll review that vignette one final time and make any other necessary changes. in the meantime, you can see how it turned out on the dev branch.

closing this issue.
