### ISSUE TITLE
Check for plane_shape documentation issues

### ISSUE THREAD

**Issue by abenefield1** [signaturescience/rplanes#143]
Checking/fixing/adding documentation that might have been impacted by the new `plane_shape()` method. Here are the places I can think to check, but let me know if you think of any others:

- [x] 1. `plane_shape()` documentation and examples
- [x] 2. `plane_score` documentation and examples
- [x] 3. interpretation vignette
- [x] 4. individual component vignette
- [x] 5. basic usage vignette
- [x] 6. shiny app

**Comment by abenefield1** [comment]
- `plane_shape()` documentation was already completed, though we may want to include the sensitivity/specificity info that we observed in preliminary analyses (e.g., "Based on preliminary analyses, the DTW method has a higher sensitivity and a slightly lower specificity than the "sdiff" method but is much more computationally expensive.")
- Made minor changes in plane_score documentation - added method argument in example where users provide non-default arguments to `plane_score()`.
- Interpretation vignette still TBD
- Added a couple of sentences to the individual component vignette under the shape section. We may want to add a subsection about comparing the two methods, but that's a larger task for the future.
- Made no edits to the basic usage vignette
- shiny app still TBD

**Comment by vpnagraj** [comment]
thanks @abenefield1 .

ive addressed the relevant items mentioned above: 

- i added a bit more to the `plane_shape()` regarding comparisons between sdiff and dtw methods (https://github.com/signaturescience/rplanes/pull/145/commits/6411d09a2a23f8fbbc7389a72cf4d2d0f0d42506)
- i changed the shiny app radio button selections to "sdiff (Default)" and "Dynamic Time Warping" (https://github.com/signaturescience/rplanes/pull/145/commits/8f90e16b4a9ea161457462737bfce7cc62b9887f)

also reminder to always make sure to run `devtools::check()` on the package when adding new features (even updates to documentation!) ... turns out that we ran into a pesky character limit in one of the examples with one of your commits. here were the check results:

```
── R CMD check results ───────────────────────────────────────────────────────────────────────────────────────── rplanes 0.0.3.9000 ────
Duration: 1m 2.6s

❯ checking Rd line widths ... NOTE
  Rd file 'plane_score.Rd':
    \examples lines wider than 100 characters:
       comp_args <- list("trend" = list("sig_lvl" = 0.05), "repeat" = list("prepend" = 4, "tolerance" = 8), "shape" = list("method" = "dtw"))

comp_args <- list("trend" = list("sig_lvl" = 0.05), "repeat" = list("prepend" = 4, "tolerance" = 8), "shape" = list("method" = "dtw"))
```

its a NOTE which would require an explanation for CRAN review. to get around that i broke up the `comp_args` object definition into a few separate lines (https://github.com/signaturescience/rplanes/pull/145/commits/fcdfc4d604b9ea06b2abdd8a51bb18abb02c74a5) ... check is coming through clean now (no NOTEs, WARNINGs, or ERRORs)
